title: Epiphany
description: > # this means to ignore newlines until "baseurl:"
  Những lời động viên sáo rỗng, mình xin không nói nhé. Để mình kể cho bạn câu chuyện của mình.
permalink: ':title/'
baseurl: '' # the subpath of your site, e.g. /blog
host: "http://keiblog.space"
url: "https://keiblog.github.io"
site-twitter: #if your site has a twitter account, enter it here
root: /
# Author Settings
author: Kei # add your name
og-img: ogimage.jpg # add your photo
author-img: kei.jpg # add your photo
about-author: "Is it you who changed <br> or is it me?" # add description
social-askfm: Kirikuro # add your Ask-fm handle
social-facebook: hoanglan.kei97 # add your Facebook handle
social-instagram: miya.kei.97 # add your Instagram handle
social-vcso: keii97 # add your VCSO handle
social-email: lehoanglan97k31@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
